### ISSUE TITLE
请问这个为何不上传到谷歌商店，使用这个会不会反弹？

### ISSUE THREAD

**Issue by xixiranran** [ineer/canClearAd#2]
第三方的，没有上传到谷歌商店的扩展好像使用会反弹，即浏览器不让使用第三方的，除非添加规则。所以你这个支持吗？为何不上传到谷歌商店呢？谢谢。

**Comment by ineer** [comment]
我还没注册谷歌应用商店开发者，所以还不能发布项目。未来的某个时间可能可以发布出去:smile:

**Comment by xixiranran** [comment]
谢谢回复，因为第三方的需要添加本地策略，很麻烦。所以就没用第三方的。你自己在用吗？自己用的话是会反弹的也就是自己变成未启用状态。所以这么好用的东西可以上传一下。支持你。

**Comment by ineer** [comment]
谢谢支持:smile:我自己在用，我这并不会反弹成为未启用状态。
没传是我还没弄双币信用卡，支付不了5$。
![123](https://cloud.githubusercontent.com/assets/20469280/19254695/07ebb600-8f89-11e6-960c-c55cb2e33ed2.JPG)

**Comment by xixiranran** [comment]
那好我安装一个
