### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by xixiranran** [ineer/canClearAd#3]
1.你可以打包成crx文件上传，这这样大家方便使用；
2.腾讯视频点选集的时候没有反应。和我之前用规则顾虑一样的问题，你看看怎么解决；
3.安装好扩展后显示关闭浏览器后他还会运行，不能随浏览器启动而启动，随浏览器关闭而关闭吗？

**Comment by ineer** [comment]
谢谢建议

对于1.我尝试打包成crx，只能拖拽进chrome://extensions，而且会提示非来自Chrome网上应用店。禁用后不能再启用，必须删除重新拖拽。而zip解压后的文件夹也可直接拖拽。

2.这个我还真没注意到腾讯的居然不能选集，刚刚试了下，发现选集后地址会变但是却不能改变集数。
察看开发者工具，选集时其它的会消失只留下3个重定向，对于这个我还不知道解决方法。第一次遇到某些http消息会消失的情况。
![xx-1](https://cloud.githubusercontent.com/assets/20469280/19262873/e2247e14-8fcb-11e6-80e8-f4e130a86878.JPG)

有一个代替的方法，只能在选集时以另个标签页打开。

3.扩展是会随浏览器关闭而关闭的，关闭后background.js的数据将丢失，如果你看到右下角有Chrome图标，可以选择不在后台运行。

**Comment by xixiranran** [comment]
你好，
1.打包好之后是对于小白来说更方便，这点其实很重要，我不知道你怎么打包的，但是我使用打包的禁用后可以启用，
2.这个方法我知道，但是着实有点麻烦了，所以能解决的话烦请通知一下；
3.既然会随浏览器关闭而关闭，那么我拖进去这个扩展后的那个提示说会后台运行，我不知道在什么地方选择，不能加一个设置界面吗？如果可以的话当然更好了。

**Comment by ineer** [comment]
1.已经打包成crx放在卡饭论坛。
2.解决了会通知你。
3.提示后台运行指的是background.js会随着浏览器开启而自动在后台运行，无法关闭的(除非禁用扩展)。

感谢你的建议:smile:
