### ISSUE TITLE
可以添加屏蔽腾讯LOL视频吗

### ISSUE THREAD

**Issue by Easy-Ez** [ineer/canClearAd#6]
http://lol.qq.com/v/

**Comment by ineer** [comment]
由于http://lol.qq.com/v/ 观看腾讯视频会跳转到其他的网站，而屏蔽规则与canClearAd原本设计的规则不同。

观看lol视频的并不是所有人，所以使用了插件的形式补充canClearAd扩展

请转到https://github.com/ineer/canClearAd-lolPlugin 下载补充插件，配合canClearAd屏蔽腾讯LOL视频广告。

**Comment by Easy-Ez** [comment]
非常感谢~
